import React from "react";
const columns = [
  {name: "#", uid: "id", sortable: true},
  {name: "NOMBRE", uid: "nombre", sortable: true},
  {name: "CUIL", uid: "cuil", sortable: true},
  {name: "TELÉFONO", uid: "telefono", sortable: true},
  {name: "DIRECCIÓN", uid: "direccion", sortable: true},
  {name: "ACCIONES", uid: "actions"},
];

// const statusOptions = [
//   {name: "Active", uid: "active"},
//   {name: "Paused", uid: "paused"},
//   {name: "Vacation", uid: "vacation"},
// ];

const users = [
  {
    id: 1,
    nombre: "Tony Reichert",
    telefono: "CEO",
    team: "Management",
    status: "active",
    cuil: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    nombre: "Zoey Lang",
    telefono: "Tech Lead",
    team: "Development",
    status: "paused",
    cuil: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    nombre: "Jane Fisher",
    telefono: "Sr. Dev",
    team: "Development",
    status: "active",
    cuil: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 4,
    nombre: "William Howard",
    telefono: "C.M.",
    team: "Marketing",
    status: "vacation",
    cuil: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    id: 5,
    nombre: "Kristen Copper",
    telefono: "S. Manager",
    team: "Sales",
    status: "active",
    cuil: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    id: 6,
    nombre: "Brian Kim",
    telefono: "P. Manager",
    team: "Management",
    cuil: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "brian.kim@example.com",
    status: "Active",
  },
  {
    id: 7,
    nombre: "Michael Hunt",
    telefono: "Designer",
    team: "Design",
    status: "paused",
    cuil: "27",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    email: "michael.hunt@example.com",
  },
  {
    id: 8,
    nombre: "Samantha Brooks",
    telefono: "HR Manager",
    team: "HR",
    status: "active",
    cuil: "31",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    email: "samantha.brooks@example.com",
  },
  {
    id: 9,
    nombre: "Frank Harrison",
    telefono: "F. Manager",
    team: "Finance",
    status: "vacation",
    cuil: "33",
    avatar: "https://i.pravatar.cc/150?img=4",
    email: "frank.harrison@example.com",
  },
  {
    id: 10,
    nombre: "Emma Adams",
    telefono: "Ops Manager",
    team: "Operations",
    status: "active",
    cuil: "35",
    avatar: "https://i.pravatar.cc/150?img=5",
    email: "emma.adams@example.com",
  },
  {
    id: 11,
    nombre: "Brandon Stevens",
    telefono: "Jr. Dev",
    team: "Development",
    status: "active",
    cuil: "22",
    avatar: "https://i.pravatar.cc/150?img=8",
    email: "brandon.stevens@example.com",
  },
  {
    id: 12,
    nombre: "Megan Richards",
    telefono: "P. Manager",
    team: "Product",
    status: "paused",
    cuil: "28",
    avatar: "https://i.pravatar.cc/150?img=10",
    email: "megan.richards@example.com",
  },
  {
    id: 13,
    nombre: "Oliver Scott",
    telefono: "S. Manager",
    team: "Security",
    status: "active",
    cuil: "37",
    avatar: "https://i.pravatar.cc/150?img=12",
    email: "oliver.scott@example.com",
  },
  {
    id: 14,
    nombre: "Grace Allen",
    telefono: "M. Specialist",
    team: "Marketing",
    status: "active",
    cuil: "30",
    avatar: "https://i.pravatar.cc/150?img=16",
    email: "grace.allen@example.com",
  },
  {
    id: 15,
    nombre: "Noah Carter",
    telefono: "IT Specialist",
    team: "I. Technology",
    status: "paused",
    cuil: "31",
    avatar: "https://i.pravatar.cc/150?img=15",
    email: "noah.carter@example.com",
  },
  {
    id: 16,
    nombre: "Ava Perez",
    telefono: "Manager",
    team: "Sales",
    status: "active",
    cuil: "29",
    avatar: "https://i.pravatar.cc/150?img=20",
    email: "ava.perez@example.com",
  },
  {
    id: 17,
    nombre: "Liam Johnson",
    telefono: "Data Analyst",
    team: "Analysis",
    status: "active",
    cuil: "28",
    avatar: "https://i.pravatar.cc/150?img=33",
    email: "liam.johnson@example.com",
  },
  {
    id: 18,
    nombre: "Sophia Taylor",
    telefono: "QA Analyst",
    team: "Testing",
    status: "active",
    cuil: "27",
    avatar: "https://i.pravatar.cc/150?img=29",
    email: "sophia.taylor@example.com",
  },
  {
    id: 19,
    nombre: "Lucas Harris",
    telefono: "Administrator",
    team: "Information Technology",
    status: "paused",
    cuil: "32",
    avatar: "https://i.pravatar.cc/150?img=50",
    email: "lucas.harris@example.com",
  },
  {
    id: 20,
    nombre: "Mia Robinson",
    telefono: "Coordinator",
    team: "Operations",
    status: "active",
    cuil: "26",
    avatar: "https://i.pravatar.cc/150?img=45",
    email: "mia.robinson@example.com",
  },
];

export {columns, users};
